name: atom_notifier
description: An easy to use value notifier wrapper with some sugar syntax
version: 1.0.3w
homepage: https://github.com/viniciusamelio/atom

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
